{
 "title": "CloudMart - Application",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "API Gateway",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{namespace=\"cloudmart-dev\", job=\"api-gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Service",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{namespace=\"cloudmart-dev\", job=\"user-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Product Service",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{namespace=\"cloudmart-dev\", job=\"product-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order Service",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{namespace=\"cloudmart-dev\", job=\"order-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate (requests/sec)",
   "type": "timeseries",
   "description": "HTTP requests per second by service",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"api-gateway\"}[5m])) by (job) or sum(rate(user_service_http_requests_total{job=\"user-service\"}[5m])) by (job) or sum(rate(product_service_requests_total{job=\"product-service\"}[5m])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "timeseries",
   "description": "Percentage of HTTP 5xx errors by service",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(http_requests_total{job=\"api-gateway\", status_code=~\"5..\"}[5m])) by (job)\r\n  /\r\n  sum(rate(http_requests_total{job=\"api-gateway\"}[5m])) by (job)\r\n  * 100\r\n)\r\nor on() vector(0)\r\nor\r\n(\r\n  sum(rate(user_service_http_requests_total{job=\"user-service\", status_code=~\"5..\"}[5m])) by (job)\r\n  /\r\n  sum(rate(user_service_http_requests_total{job=\"user-service\"}[5m])) by (job)\r\n  * 100\r\n)\r\nor on() vector(0)\r\nor\r\n(\r\n  sum(rate(product_service_requests_total{job=\"product-service\", status=~\"5..\"}[5m])) by (job)\r\n  /\r\n  sum(rate(product_service_requests_total{job=\"product-service\"}[5m])) by (job)\r\n  * 100\r\n)\r\nor on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Duration (Latency)",
   "type": "timeseries",
   "description": "HTTP request latenct - p50, p95, p99 percentiles",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, \r\n  sum(rate(http_request_duration_seconds_bucket{job=\"api-gateway\"}[5m])) by (le, job)\r\n) * 1000\r\nor\r\nhistogram_quantile(0.50, \r\n  sum(rate(user_service_http_request_duration_seconds_bucket{job=\"user-service\"}[5m])) by (le, job)\r\n) * 1000\r\nor\r\nhistogram_quantile(0.50, \r\n  sum(rate(product_service_request_duration_seconds_bucket{job=\"product-service\"}[5m])) by (le, job)\r\n) * 1000",
     "legendFormat": "{{job}} - p50"
    },
    {
     "expr": "histogram_quantile(0.95, \r\n  sum(rate(http_request_duration_seconds_bucket{job=\"api-gateway\"}[5m])) by (le, job)\r\n) * 1000\r\nor\r\nhistogram_quantile(0.95, \r\n  sum(rate(user_service_http_request_duration_seconds_bucket{job=\"user-service\"}[5m])) by (le, job)\r\n) * 1000\r\nor\r\nhistogram_quantile(0.95, \r\n  sum(rate(product_service_request_duration_seconds_bucket{job=\"product-service\"}[5m])) by (le, job)\r\n) * 1000",
     "legendFormat": "{{job}} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, \r\n  sum(rate(http_request_duration_seconds_bucket{job=\"api-gateway\"}[5m])) by (le, job)\r\n) * 1000\r\nor\r\nhistogram_quantile(0.99, \r\n  sum(rate(user_service_http_request_duration_seconds_bucket{job=\"user-service\"}[5m])) by (le, job)\r\n) * 1000\r\nor\r\nhistogram_quantile(0.99, \r\n  sum(rate(product_service_request_duration_seconds_bucket{job=\"product-service\"}[5m])) by (le, job)\r\n) * 1000",
     "legendFormat": "{{job}} - p99"
    }
   ]
  },
  {
   "title": "HTTP Methods Distribution",
   "type": "piechart",
   "description": "Request rate by HTTP method",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"api-gateway\"}[5m])) by (method)\r\nor\r\nsum(rate(user_service_http_requests_total{job=\"user-service\"}[5m])) by (method)\r\nor\r\nsum(rate(product_service_requests_total{job=\"product-service\"}[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Slowest Routes",
   "type": "bargauge",
   "description": "Average latency by endpoint",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5,\r\n  avg(rate(http_request_duration_seconds_sum{job=\"api-gateway\"}[5m])) by (route)\r\n  /\r\n  avg(rate(http_request_duration_seconds_count{job=\"api-gateway\"}[5m])) by (route)\r\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}