{
 "title": "CloudMart - Business Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Service Health",
   "type": "stat",
   "description": "Percentage of services running",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(up{namespace=\"cloudmart-dev\"} == 1) / count(up{namespace=\"cloudmart-dev\"})) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Platform Success Rate",
   "type": "gauge",
   "description": "Percentage of successful requests (SLO)",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(http_requests_total{namespace=\"cloudmart-dev\", status_code=~\"[23]..\"}[5m]))\r\n  /\r\n  sum(rate(http_requests_total{namespace=\"cloudmart-dev\"}[5m]))\r\n) * 100\r\nor\r\n(\r\n  sum(rate(user_service_http_requests_total{namespace=\"cloudmart-dev\", status_code=~\"[23]..\"}[5m]))\r\n  /\r\n  sum(rate(user_service_http_requests_total{namespace=\"cloudmart-dev\"}[5m]))\r\n) * 100\r\nor\r\n(\r\n  sum(rate(product_service_requests_total{namespace=\"cloudmart-dev\", status=~\"[23]..\"}[5m]))\r\n  /\r\n  sum(rate(product_service_requests_total{namespace=\"cloudmart-dev\"}[5m]))\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Platform Requests",
   "type": "stat",
   "description": "Requests per minute across all services",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"cloudmart-dev\"}[5m])) * 60\r\nor\r\nsum(rate(user_service_http_requests_total{namespace=\"cloudmart-dev\"}[5m])) * 60\r\nor\r\nsum(rate(product_service_requests_total{namespace=\"cloudmart-dev\"}[5m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 API Endpoints (by usage)",
   "type": "bargauge",
   "description": "Most popular API routes",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(topk(5, sum(rate(http_requests_total{job=\"api-gateway\"}[5m])) by (route)) * 60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Product Views (per minute)",
   "type": "timeseries",
   "description": "Product catalog activity",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(product_service_requests_total{namespace=\"cloudmart-dev\", exported_endpoint=~\"/products.*\"}[5m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}