{
 "title": "CloudMart - Infrastructure",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "description": "Overall CPU utilization percentage",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "description": "Memory utilization percentage",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Count per Deployment",
   "type": "stat",
   "description": "Number of running pods for each service",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"cloudmart-dev\"}) by (created_by_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Usage by Namespace",
   "type": "timeseries",
   "description": "CPU consumption per namespace in cores",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace!=\"\"}[5m])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory Usage by Namespace",
   "type": "timeseries",
   "description": "Memory consumption per namespace",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Mib" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace!=\"\"}) by (namespace) / (1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restart Count",
   "type": "timeseries",
   "description": "Total container restarts per pod (crashes)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"cloudmart-dev\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}